create table sensor(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar(30) check ( length(name) > 3 ) UNIQUE,
                       created_at timestamp NOT NULL
);

create table measurement(
                            id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                            sensor_name varchar(30) REFERENCES sensor(name) ON DELETE CASCADE,
                            value numeric(2) check ( value > -101 and value < 101 ),
                            raining bool NOT NULL,
                            added_at timestamp not null
);